### ISSUE TITLE
Firework in 3d

### ISSUE THREAD

**Issue by havi05** [hinek/fireworks2020#1]
Your fireworks look especially good. Please also create a 3d project. (I saw it in the videodescription and need a tutorial in 3d to understand)

Sorry if I make spelling mistakes,
Gamemap

**Comment by hinek** [comment]
Hi, thank you, that's very nice. I created a 3D project now, you can find it here:
[https://github.com/hinek/fireworks3d](https://github.com/hinek/fireworks3d)

I also made a video tutorial, it's on youtube:
[https://www.youtube.com/watch?v=ix5xXHN8OQk](https://www.youtube.com/watch?v=ix5xXHN8OQk)

**Comment by havi05** [comment]
Thank you very much!
