### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by chucklepie** [hinek/fireworks2020#3]
This isn't an issue, just wanted to say the library is lovely and I've used it in the ending of my game, which is a remake of a very old ZX Spectrum game. I couldn't find any other contact information.

I've butchered it a bit for my (completely free and opensource, I'm not advertising) game, and and gave it a 4 colour palette and removed all the nice world environments, i.e. it's now not as good and looks rubbish ;-)

A brief sample is here, btw. Please delete this issue if you don't want to see it further.

https://twitter.com/chucklepie/status/1439638488169787393

**Comment by hinek** [comment]
Hey thanks for the info, I'm glad you could use it.
